import{a as L,S as w,i as n}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="48293638-4d2a22c69cd32ab6d85c7a697",v="https://pixabay.com/api/";async function g(t,o=1,s=15){const a={key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s};try{const{data:e}=await L.get(v,{params:a});return e}catch{throw new Error("Failed to fetch images")}}let u;function y(t){const o=document.getElementById("gallery"),s=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:c,views:p,comments:b,downloads:E})=>`
        <a href="${e}" class="gallery-item">
          <img src="${a}" alt="${r}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${c}</p>
            <p><b>Views:</b> ${p}</p>
            <p><b>Comments:</b> ${b}</p>
            <p><b>Downloads:</b> ${E}</p>
          </div>
        </a>
      `).join("");o.insertAdjacentHTML("beforeend",s),u?u.refresh():u=new w(".gallery a")}function I(){document.getElementById("gallery").innerHTML=""}function i(t){document.getElementById("loader").classList.toggle("hidden",!t)}const P=document.getElementById("search-form"),h=document.getElementById("load-more");let l=1,m="",d=0;const f=t=>{h.classList.toggle("hidden",!t)};P.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.query.value.trim();if(!o){n.error({title:"Error",message:"Please enter a search term."});return}m=o,l=1,I(),i(!0),f(!1);try{const{hits:s,totalHits:a}=await g(m,l);if(i(!1),s.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}d=a,y(s),n.success({title:"Success",message:`Hooray! We found ${d} images.`}),l*15<d&&f(!0)}catch(s){i(!1),n.error({title:"Error",message:s.message})}});h.addEventListener("click",async()=>{l+=1,i(!0);try{const{hits:t}=await g(m,l);i(!1),y(t),l*15>=d?(f(!1),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):$()}catch(t){i(!1),n.error({title:"Error",message:t.message})}});const $=()=>{const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
